In [2]:
from nltk.tokenize import  word_tokenize
import pandas as pd
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [7]:
#Creating Bag of Words manually

sent1 = "It is a good practice for us."
sent2 = "It was also good to know about it."

sent = sent1 + " " + sent2
words = list(set(word_tokenize(sent.lower())))

s1 = []
s2 = []

for word in words:
    s1.append(word_tokenize(sent1.lower()).count(word))

for word in words:
    s2.append(word_tokenize(sent2.lower()).count(word))

print(words)
print(s1)
print(s2)

bog = pd.DataFrame({'words' : words})
bog['sent1'] = s1
bog['sent2'] = s2

df =  pd.DataFrame({},index=['sent1','sent2'], columns=bog['words'])
df.iloc[0,:] = s1
df.iloc[1,:] = s2

df

['practice', 'is', 'a', 'us', 'it', 'for', 'to', '.', 'good', 'was', 'know', 'about', 'also']
[1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0]
[0, 0, 0, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1]


words practice is  a us it for to  . good was know about also
sent1        1  1  1  1  1   1  0  1    1   0    0     0    0
sent2        0  0  0  0  2   0  1  1    1   1    1     1    1

**Using in-built library**

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
cvt = CountVectorizer()
x_new = cvt.fit_transform([sent1,sent2])

x_new.toarray()

array([[0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0],
       [1, 1, 0, 1, 0, 2, 1, 0, 1, 0, 1]])

In [18]:
cvt.get_feature_names_out()

array(['about', 'also', 'for', 'good', 'is', 'it', 'know', 'practice',
       'to', 'us', 'was'], dtype=object)

In [21]:
df = pd.DataFrame(data=x_new.toarray(),columns=cvt.get_feature_names_out())

In [22]:
df

about  also  for  good  is  it  know  practice  to  us  was
0      0     0    1     1   1   1     0         1   0   1    0
1      1     1    0     1   0   2     1         0   1   0    1

In [25]:
new = 'It was good for us'
new_features = cvt.transform([new])
new_features.toarray()

array([[0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1]])

N-grams

In [27]:
help(CountVectorizer)

Help on class CountVectorizer in module sklearn.feature_extraction.text:

class CountVectorizer(_VectorizerMixin, sklearn.base.BaseEstimator)
 |  CountVectorizer(*, input='content', encoding='utf-8', decode_error='strict', strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, stop_words=None, token_pattern='(?u)\\b\\w\\w+\\b', ngram_range=(1, 1), analyzer='word', max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=<class 'numpy.int64'>)
 |  
 |  Convert a collection of text documents to a matrix of token counts.
 |  
 |  This implementation produces a sparse representation of the counts using
 |  scipy.sparse.csr_matrix.
 |  
 |  If you do not provide an a-priori dictionary and you do not use an analyzer
 |  that does some kind of feature selection then the number of features will
 |  be equal to the vocabulary size found by analyzing the data.
 |  
 |  For an efficiency comparison of the different feature extractors, see
 |  :ref:`sphx_glr_au

In [49]:
ngram = CountVectorizer(ngram_range=(1,2)) #min=1, max=2

In [50]:
new_ng = ngram.fit_transform([sent1,sent2])
print(new_ng.toarray())
print(ngram.get_feature_names_out())

[[0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 0 1 0 0]
 [1 1 1 1 0 0 1 0 1 0 0 2 0 1 1 1 0 0 1 1 0 1 1]]
['about' 'about it' 'also' 'also good' 'for' 'for us' 'good'
 'good practice' 'good to' 'is' 'is good' 'it' 'it is' 'it was' 'know'
 'know about' 'practice' 'practice for' 'to' 'to know' 'us' 'was'
 'was also']


In [51]:
ndf = pd.DataFrame(data=new_ng.toarray(),columns=ngram.get_feature_names_out())
ndf

about  about it  also  also good  for  for us  good  good practice  \
0      0         0     0          0    1       1     1              1   
1      1         1     1          1    0       0     1              0   

   good to  is  ...  it was  know  know about  practice  practice for  to  \
0        0   1  ...       0     0           0         1             1   0   
1        1   0  ...       1     1           1         0             0   1   

   to know  us  was  was also  
0        0   1    0         0  
1        1   0    1         1  

[2 rows x 23 columns]